function createaxes(X1, YMatrix1, X2, YMatrix2, X3, YMatrix3, X4, Y1, X5, X6, Y2, X7, X8, Y3, X9, X10, Y4, X11, X12, Y5, X13)
%CREATEAXES(X1, YMatrix1, X2, YMatrix2, X3, YMatrix3, X4, Y1, X5, X6, Y2, X7, X8, Y3, X9, X10, Y4, X11, X12, Y5, X13)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  YMATRIX2:  matrix of y data
%  X3:  vector of x data
%  YMATRIX3:  matrix of y data
%  X4:  vector of x data
%  Y1:  vector of y data
%  X5:  vector of x data
%  X6:  vector of x data
%  Y2:  vector of y data
%  X7:  vector of x data
%  X8:  vector of x data
%  Y3:  vector of y data
%  X9:  vector of x data
%  X10:  vector of x data
%  Y4:  vector of y data
%  X11:  vector of x data
%  X12:  vector of x data
%  Y5:  vector of y data
%  X13:  vector of x data

%  Auto-generated by MATLAB on 04-Jul-2018 13:59:01

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,...
    'Color',[0.498039215686275 0.498039215686275 0.498039215686275]);
set(plot1(9066),'LineWidth',2,'Color',[0 0 0]);
set(plot1(12082),'LineWidth',2,'Color',[0 0 0]);
set(plot1(14083),'LineWidth',2,'Color',[0 0 0]);
set(plot1(15984),'LineWidth',2,'Color',[0 0 0]);
set(plot1(18135),'LineWidth',2,'Color',[0 0 0]);

% Create multiple lines using matrix input to plot
plot2 = plot(X2,YMatrix2,...
    'Color',[0.498039215686275 0.498039215686275 0.498039215686275]);
set(plot2(9066),'LineWidth',2,'Color',[0 0 0]);
set(plot2(12082),'LineWidth',2,'Color',[0 0 0]);
set(plot2(14083),'LineWidth',2,'Color',[0 0 0]);
set(plot2(15984),'LineWidth',2,'Color',[0 0 0]);
set(plot2(18135),'LineWidth',2,'Color',[0 0 0]);

% Create text
text('String','   80.90 s / 2.61%','Position',[-190.631720430108 -0.3 0]);

% Create text
text('String','121.20 s / 2.59%','Position',[-190 -0.7 0]);

% Create multiple lines using matrix input to plot
plot(X3,YMatrix3,'LineStyle','--','Color',[0 0 0]);

% Create plot
plot(X4,Y1,'Color',[0 0 0]);

% Create plot
plot(X5,Y1,'Color',[0 0 0]);

% Create text
text('String','  81.90 s / 2.46%','Position',[-190 1.2 0]);

% Create text
text('String','122.20 s / 2.46%','Position',[-190 0.8 0]);

% Create plot
plot(X6,Y2,'Color',[0 0 0]);

% Create plot
plot(X7,Y2,'Color',[0 0 0]);

% Create text
text('String','  80.15 s / 2.96%','Position',[-200 2.7 0]);

% Create text
text('String','120.70 s / 2.93%','Position',[-200 2.3 0]);

% Create plot
plot(X8,Y3,'Color',[0 0 0]);

% Create plot
plot(X9,Y3,'Color',[0 0 0]);

% Create text
text('String','  79.90 s / 3.08%','Position',[-200 4.2 0]);

% Create text
text('String','120.20 s / 3.02%','Position',[-200 3.8 0]);

% Create plot
plot(X10,Y4,'Color',[0 0 0]);

% Create plot
plot(X11,Y4,'Color',[0 0 0]);

% Create text
text('String','  81.65 s / 2.43%','Position',[-200 5.7 0]);

% Create text
text('String','121.95 s / 2.42%','Position',[-200 5.3 0]);

% Create plot
plot(X12,Y5,'Color',[0 0 0]);

% Create plot
plot(X13,Y5,'Color',[0 0 0]);

% Create text
text('String','Region A','Position',[-200 6.2 0]);

% Create text
text('String','Region B','Position',[-200 4.7 0]);

% Create text
text('String','Region C','Position',[-200 3.2 0]);

% Create text
text('String','Region D','Position',[-200 1.7 0]);

% Create text
text('String','All Regions','Position',[-200 0.2 0]);

% Create xlabel
xlabel('Time (s)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-200 35]);
% Set the remaining axes properties
set(axes1,'XMinorTick','on','YColor',[1 1 1],'YTickLabel','');
