#!/bin/sh
# plot_grd
# sh plot_amp_grd txt_file with longitude, latitude and amplitude ratio
#
# Yong ZHOU
# zhouy3@sustc.edu.cn
# 2017-09-16

txt=$1
grd=${txt}.grd

surface -Rg -I0.2/0.2 -G${grd} ${txt}

#of=`echo $grd | gawk -F. '{print $1$2}'`
of=$grd

echo $grd $of

title=`echo $grd | gawk -F. '{print $1}'`

R=g

#min=`grdinfo $grd | grep z_min | gawk '{print $3}'`
#max=`grdinfo $grd | grep z_min | gawk '{print $5}'`
#min=-25.6 # add by yzhou 20200502
#max=99.4
min=-25.4
max=93.1

psbasemap -R$R -JN180/5i -Bg30/g30:."$title": -K -P > ${of}.ps
#grd2cpt $grd -Cjet -Z > tmp.cpt
makecpt -Cjet -T${min}/${max}/0.001 -Z >tmp.cpt
#makecpt -Cjet -T-19.7/97/0.001 -Z >tmp.cpt

grdimage $grd -R -J -Bg30/g30 -Ctmp.cpt -K -O -fg >> ${of}.ps
pscoast -R -J -Dc -Wblack -K -O >> ${of}.ps

psscale -D5.2i/1.2i/2.2i/0.1i -Ctmp.cpt -Ba20f5/:"Amplitude ratio (%)": -K -O >> ${of}.ps
psxy -R -J -T -O >> ${of}.ps

ps2raster -Tg -A ${of}.ps
ps2raster -Tf -A ${of}.ps
evince ${of}.pdf
